services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: faroc
      POSTGRES_PASSWORD: changeit
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - gymanager
    restart: unless-stopped
  gymanager:
    image: gymanager:0.0.1-SNAPSHOT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gymanager
      - SPRING_DATASOURCE_USERNAME=faroc
      - SPRING_DATASOURCE_PASSWORD=changeit
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/gymanager
      - SPRING_FLYWAY_USER=faroc
      - SPRING_FLYWAY_PASSWORD=changeit
    ports:
      - "8080:8080"
    networks:
      - gymanager
    depends_on:
      - postgres

volumes:
  postgres:

networks:
  gymanager:
    driver: bridge