@host = http://localhost:8080
@adminId = 43629828-9b70-497b-90fb-7b6cdd8e6147
@token = eyJhbGciOiJSUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJneW1zOmNyZWF0ZSIsImd5bXM6dXBkYXRlIl0sImFkbWluX2lkIjoiMjczODA5YWYtOWE5Yi00MGEyLWE4ZWMtNGMxYzRmZTZlODQ3Iiwicm9sZXMiOlsiQURNSU4iXSwiaXNzIjoiZ3ltYW5hZ2VyLWFwaSIsIm5hbWUiOiJGYWJpbyIsImlkIjoiZDdkMjkxNWEtYmRiMC00MTdlLTk1NDItM2QyMDViNzJlMDAzIiwiZXhwIjoxNzE4NDg5MjIzLCJpYXQiOjE3MTg0ODU2MjMsImZhbWlseV9uYW1lIjoiTGFuem9uaSIsImVtYWlsIjoicmVhbGZhYmlvQG1vZGVsLmNvbSJ9.qZrc-_glHIOcIuKFSUlOBWHa6Yek1IXcwPv6p1UbYPDgMFqsE_nJ1e77-hbdfckE8whTeh6wPzB9ybV3NQUvAP2Dmp9NjGuvYdtCMMetS3BXNeFjkoPN2TlyFy7KMKXdgBhgxT_D8ivAS1Q6W8v7oRR2rSbNbLLwqHiMIQ1VkdaatY2OMHXhOKzxs6IFqZh9O4If5tCaJLYRsRjJRKYxaaiiPmanAxUCmMnaX9YJh1Cpy1TKn9KNWGRWBIkV9XQkOSq8jpl70mMQcgAq_6MomddJgwFSR2JAfWS-F0BcGHxvlba0jYIISAt6rp-EmmewKSIx4TPPzB_-sbcrTclEVw

POST {{host}}/subscriptions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "subscriptionType": "Free",
  "adminId": "{{adminId}}"
}