@host = http://localhost:8080
@subscriptionId = 5f8aaddf-3dc8-48c1-beba-8f412e78e327
@token = eyJhbGciOiJSUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJneW1zOmNyZWF0ZSIsImd5bXM6dXBkYXRlIl0sImFkbWluX2lkIjoiMjczODA5YWYtOWE5Yi00MGEyLWE4ZWMtNGMxYzRmZTZlODQ3Iiwicm9sZXMiOlsiQURNSU4iXSwiaXNzIjoiZ3ltYW5hZ2VyLWFwaSIsIm5hbWUiOiJGYWJpbyIsImlkIjoiZDdkMjkxNWEtYmRiMC00MTdlLTk1NDItM2QyMDViNzJlMDAzIiwiZXhwIjoxNzE4NTc5OTIzLCJpYXQiOjE3MTg1NzYzMjMsImZhbWlseV9uYW1lIjoiTGFuem9uaSIsImVtYWlsIjoicmVhbGZhYmlvQG1vZGVsLmNvbSJ9.FVFUmvaIYdQlZ9qVmDFJJX4N1sjv3CZQLm9sNmN1TYvRgZkV-zIfZJOuAP2bS7V_T1HQ8VXF4f0HdwdqzTZgP9EPr6vD36vyKIYcZ5-omOf4QCHaWU9sYcnc0JRJSA_KbH_uHpj3ILG8xxyoEZMTZcOOjBl0A00fsAkNKkz9V7fD361zUPi21gBK8pFQVB2XuXtnz15eDqCEwbYxeDpk9p7ZsKOz85aktSG-z_d0ZvQ4LUXMpR4WCkpE3I27TBaiXctaVHceP5JfzC369kLKBNdH6Wl_FIuKx_64S7JZxGpQK0qiAZmlGs71ytZf2fE32U80RvY5PyXodVjfMPFC-Q

DELETE {{host}}/subscriptions/{{subscriptionId}}
Content-Type: application/json
Authorization: Bearer {{token}}