@host = http://localhost:8080
@userId = d7d2915a-bdb0-417e-9542-3d205b72e003
@token = eyJhbGciOiJSUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJneW1zOmNyZWF0ZSIsImd5bXM6dXBkYXRlIl0sImFkbWluX2lkIjoiMjczODA5YWYtOWE5Yi00MGEyLWE4ZWMtNGMxYzRmZTZlODQ3Iiwicm9sZXMiOlsiQURNSU4iXSwiaXNzIjoiZ3ltYW5hZ2VyLWFwaSIsIm5hbWUiOiJGYWJpbyIsImlkIjoiZDdkMjkxNWEtYmRiMC00MTdlLTk1NDItM2QyMDViNzJlMDAzIiwiZXhwIjoxNzE4NDA4NzUzLCJpYXQiOjE3MTg0MDUxNTMsImZhbWlseV9uYW1lIjoiTGFuem9uaSIsImVtYWlsIjoicmVhbGZhYmlvQG1vZGVsLmNvbSJ9.blhYEKfyRLjITnTlXoyvAsxOGhncSlMgY2lOdUEBYwvmLIkE1CKB8pBTFvKYJNldwZw15wApbPcKWyHp6zLmYKbiOMMqXmKkJ-Ng407BJeZff0jpqWeT4wnde_Xbkd4621jw8oJGE1hdV8pwprOLmdHxv2mp4J1HY4K1kLxcLpXg2YuWhji2f-GsolBpW3E-IYm8p6Lc0eFc-Vkl3h0alqzJus8oastXsV420W-rfFQtPQYH0v4MeqoagGljSKSqadAS-lRt_aflI9rBIHZBSSaR_gmsWuHJgFePZAQmSYzgmrAfwwetPxGWWwS1OUlemcmcTn-ww6WKhrRKLKYAMQ

POST {{host}}/users/{{userId}}/profiles/admin
Content-Type: application/json
Authorization: Bearer {{token}}