@host = http://localhost:8080
@subscriptionId = 3a5242f4-17c2-49ea-824b-58dd8f6c1fc2
@token = eyJhbGciOiJSUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJneW1zOmNyZWF0ZSIsImd5bXM6dXBkYXRlIl0sImFkbWluX2lkIjoiMjczODA5YWYtOWE5Yi00MGEyLWE4ZWMtNGMxYzRmZTZlODQ3Iiwicm9sZXMiOlsiQURNSU4iXSwiaXNzIjoiZ3ltYW5hZ2VyLWFwaSIsIm5hbWUiOiJGYWJpbyIsImlkIjoiZDdkMjkxNWEtYmRiMC00MTdlLTk1NDItM2QyMDViNzJlMDAzIiwiZXhwIjoxNzE4NjY5MTAyLCJpYXQiOjE3MTg2NjU1MDIsImZhbWlseV9uYW1lIjoiTGFuem9uaSIsImVtYWlsIjoicmVhbGZhYmlvQG1vZGVsLmNvbSJ9.u_XMUfNVSlz7fy9YtdXaspU9iO0fTH-y3qWEkQx0r4i6-N26zb8XbqkeDZzwbVMShbcqkAU2xGpxTge4PK53sJfAWi5MhMUFRQRduH1JtYO2W_jSeGkLlznLBHG63_za_HgEV9O5oGm6i7YsPM2D10GQ_2vnIzumba4R2n99dWS0QDko3FHZ3QoupcVLC_UuY24yXXABx3ucksKSRw0JNXVpM_dzBk33b0Za50pJHiW2ZZLvqWodOhkecHgyLNOW01T2Jo4SpF48dVRCbRk6m089Zxi88ICENXtMWoNxH4j6EtU2tMwAwwkbJXdCEMVCtQBk0nSSYLJkgZOFy2pxYw

POST {{host}}/subscriptions/{{subscriptionId}}/gyms
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Fitness House"
}